application:
    api_key:
    api_path: /api
    databases:
        default:
    encryption:
        enabled: false
        private_key: ''
    logging:
        backup_count: 5
        datefmt: '%Y-%m-%d %H:%M:%S'
        file: maastro_test.log
        format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
        level: DEBUG
        max_size: 1024
        use_console: true
    port: '5000'
    server_url: http://host.docker.internal
    task_dir: tasks
    environments:
    acc: {}
    dev: {}
    prod: {}
    test: {}